---
- name: Basic server validation
  hosts: app_servers
  gather_facts: true

  tasks:
    - name: Show hostname
      ansible.builtin.debug:
        var: ansible_facts["hostname"]

    - name: Learn failure handling
      block:

        - name: Intentionally fail
          ansible.builtin.command:
            cmd: hostname
          changed_when: false

      rescue:

        - name: Show rescue message
          ansible.builtin.debug:
            msg: "The block failed. Rescue is running."

      always:

        - name: Show always message
          ansible.builtin.debug:
            msg: "Always runs regardless of the result."


