---
- name: Check Docker service status
  ansible.builtin.service_facts:
  when: inventory_hostname in groups['docker_servers']

- name: Validate docker services status before patching
  ansible.builtin.assert:
    that:
      - ansible_facts.services['docker.service'].state == "running"
    success_msg: "Docker services is running."
    fail_msg: "Docker services is not running."
  when: inventory_hostname in groups['docker_servers']
