---
- name: Check PostgreSQL
  become: true
  ansible.builtin.command: docker exec {{ postgres_container }} pg_isready
  register: postgres_health
  changed_when: false
  when: inventory_hostname in groups['postgres_servers']

- name: Validate PostgreSQL
  ansible.builtin.assert:
    that:
      - postgres_health.rc == 0
    success_msg: "PostgreSQL is accepting connections."
    fail_msg: "PostgreSQL is not accepting connections."
  when: inventory_hostname in groups['postgres_servers']

- name: Test the postgres connection
  become: true
  ansible.builtin.command:
    cmd: docker exec -i {{ postgres_container }} psql -U {{ postgres_ansible_user }} -d {{ postgres_database }} -c "SELECT CURRENT_TIMESTAMP"
  changed_when: false
  when: inventory_hostname in groups['postgres_servers']
  register: postgres_timestamp

- name: Validation for PostgreSQL authentication & connection
  ansible.builtin.assert:
    that:
      - postgres_timestamp.rc == 0
    success_msg: "PostgreSQL is accepting connection and can be authenticated"
    fail_msg: "PostgreSQL is not accepting connection"
  when: inventory_hostname in groups['postgres_servers']
